kalori/urls.py
from django.urls import path

from . import views

app_name = 'kalori'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:food_id>/', views.detail, name='detail'),
]

todoappdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('kalori.urls')),
    path('kalori/', include('kalori.urls')),
    path('admin/', admin.site.urls),
]

kalori/models.py
from django.db import models


class Food(models.Model):
    name = models.CharField(max_length=200)
    calories = models.FloatField(default=0)
    carbs = models.FloatField(default=0)
    cholestrol = models.FloatField(default=0)
    fat = models.FloatField(default=0)
    fiber = models.FloatField(default=0)
    protein = models.FloatField(default=0)
    sat_fat = models.FloatField(default=0)
    sugar = models.FloatField(default=0)

    def __str__(self):
        return self.name

kalori/views.py
from django.shortcuts import get_object_or_404, render
import csv

from kalori.models import Food


def index(request):
    food_list = Food.objects.order_by('-id')[:5]
    context = {
        'food_list': food_list,
    }
    return render(request, 'kalori/index.html', context)


def detail(request, food_id):
    food = get_object_or_404(Food, pk=food_id)
    return render(request, 'kalori/detail.html', {'food': food})


def upload_csv():
    with open('DataKalori.csv') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            _, created = Food.objects.update_or_create(
                name=row[0],
                calories=float(row[1]),
                carbs=float(row[4]),
                cholestrol=float(row[7]),
                fat=float(row[2]),
                fiber=float(row[6]),
                protein=float(row[3]),
                sat_fat=float(row[8]),
                sugar=float(row[5])
            )

kalori/templates/kalori/detail.html
<!DOCTYPE html>
<html lang="en">
{% include "kalori/head/head.html" %}
<body>
    {% include "kalori/navbar/navbar.html" %}
    <h1>{{ food.name }}</h1>
    {% include "kalori/food_detail/food_detail.html" %}
</body>
</html>

kalori/templates/kalori/food_detail/food_detail.html
<div class="foodContainer">
    <div class="outline">
        <div class="outlineSearch">
            <div class="searchItem searchDropdown">
                <select class="ui dropdown">
                  <option value="">Gender</option>
                  <option value="1">Male</option>
                  <option value="0">Female</option>
                </select>
            </div>
            <div class="searchItem searchBar">
                <div>
                    <input id="searchFood" type="text" placeholder="Kalori Food...">
                    <i class="search link icon"></i>
                </div>
            </div>
        </div>
        <div class="outlineAnalytics">
            here goes analytic details
        </div>
        <div class="foodContainer outlineFood">
            <div>{{ food.name }}</div>
            <div class="foodDetails">
                <div class="nutritionBar">Nutrition Details</div>
                <div class="foodItem">Calories: {{ food.calories }}</div>
                <div class="foodItem">Carbohydrates: {{ food.carbs }}</div>
                <div class="foodItem">Cholesterol: {{ food.cholestrol }}</div>
                <div class="foodItem">Fat: {{ food.fat }}</div>
                <div class="foodItem">Fiber: {{ food.fiber }}</div>
                <div class="foodItem">Protein: {{ food.protein }}</div>
                <div class="foodItem">Saturated Fat: {{ food.sat_fat }}</div>
            </div>
        </div>
    </div>
    <div class="dailyNutrition">
        <div class="nutritionBar">Daily Nutrition</div>
        <div class="nutritionItem">Calories: {{ food.calories }}</div>
        <div class="nutritionItem">Carbohydrates: {{ food.carbs }}</div>
        <div class="nutritionItem">Cholesterol: {{ food.cholestrol }}</div>
        <div class="nutritionItem">Fat: {{ food.fat }}</div>
        <div class="nutritionItem">Fiber: {{ food.fiber }}</div>
        <div class="nutritionItem">Protein: {{ food.protein }}</div>
        <div class="nutritionItem">Saturated Fat: {{ food.sat_fat }}</div>
    </div>
</div>

kalori/templates/kalori/head/head.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<head>
    <meta charset="UTF-8">
    <title>Kalori App</title>
    {% include "kalori/head/linksCSS.html" %}
</head>

<!--</html>-->

kalori/templates/kalori/head/linksCSS.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'kalori/detail.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'kalori/navbar/navbar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'kalori/food_detail/food_detail.css' %}">

kalori/templates/kalori/index.html
<!DOCTYPE html>
<html lang="en">
{% include "kalori/head/head.html" %}
<body>
{% if food_list %}
    <ul>
    {% for food in food_list %}
        <li><a href="{% url 'kalori:detail' food.id %}">{{ food.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No foods are available.</p>
{% endif %}
</body>
</html>

kalori/templates/kalori/navbar/navbar.html
<div class="ui pointing menu">
    <div>
        <a class="active item">
            Home
        </a>
    </div>
    <div>
        <a class="item">
            Your Kalori
        </a>
    </div>
    <div>
        <a class="item">
            About
        </a>
    </div>

    <div class="right menu">
        <div class="item">
            <div class="ui transparent icon input">
                <input type="text" placeholder="Search your Food">
                <i class="search link icon"></i>
            </div>
        </div>
    </div>
</div>